### ISSUE TITLE
New character was given items old charatcer did not have

### ISSUE THREAD

**Issue by eTzmNcbkrng** [55Honey/Acore_CarbonCopy#6]
Following presented with Tauren Hunters and Orc Warriors:

Create two characters, same race and class
Entered world on one
`.addlevel 18`
`.carboncopy $OtherChar`
*wait for message saying it's safe to log out*
`/logout`
Login on secondary character.
Go to mailbox: `.tele Orgrimmar`

Copy characters are given a bunch of Recruit's Shirts (Item ID 38) that the original character did not have.

![image](https://user-images.githubusercontent.com/26512802/114961021-56121d00-9ebc-11eb-8f91-dee2e370b08d.png)
![image](https://user-images.githubusercontent.com/26512802/114961081-7215be80-9ebc-11eb-8e34-0e26bbc10252.png)

**Comment by 55Honey** [comment]
That's a feature. If the character would wear Something in all Slots, these shirts would be replaced.
